
<header class="contact">

	<div class="humongous-title">
		<h1 class="h1 bold-and-light">
			<?= $contact->fancy_title ?>
		</h1>
	</div>

	<div class="paths">
		<?
			$leftCaption   = \App\ViewHelper::splitContactPathCaption($contact->left_text);
			$middleCaption = \App\ViewHelper::splitContactPathCaption($contact->middle_text);
			$rightCaption  = \App\ViewHelper::splitContactPathCaption($contact->right_text);
		?>


		<div class="icon-container left">
			<div class="image" style="background-image: url('<?= $_baseurl . 'img/contact_heart.svg' ?>')"></div>

			<div class="title">
				<?= $contact->left_title ?>
			</div>

			<div class="caption custom-text-content">
				<?= $leftCaption[0] ?>
			</div>

			<div class="details custom-text-content">
				<?= $leftCaption[1] ?>
			</div>
		</div>

		<div class="icon-container middle">
			<div class="image" style="background-image: url('<?= $_baseurl . 'img/contact_matthijs.svg' ?>')"></div>

			<div class="title">
				<?= $contact->middle_title ?>
			</div>

			<div class="caption custom-text-content">
				<?= $middleCaption[0] ?>
			</div>

			<div class="details custom-text-content">
				<?= $middleCaption[1] ?>
			</div>
		</div>

		<div class="icon-container right">
			<div class="image" style="background-image: url('<?= $_baseurl . 'img/contact_rocket.svg' ?>')"></div>

			<div class="title">
				<?= $contact->right_title ?>
			</div>

			<div class="caption custom-text-content">
				<?= $rightCaption[0] ?>
			</div>

			<div class="details custom-text-content">
				<?= $rightCaption[1] ?>
			</div>
		</div>

	</div>

</header>


<section class="contact-form-and-address large-margin-column">

	<section class="contact-form-container appear-effect">

		<h3 class="h2">
			<?= $contact->form_title ?>
		</h3>

		<div class="text custom-text-content">
			<?
				echo \App\ViewHelper::replaceContentPlaceHolders($contact->form_text);
			?>
		</div>

		<hr>

		<div id="contact-form-thanks">
			<?= ML::label('contact thanks') ?>
		</div>

		<div id="contact-form-container" class="basic-form contact-form">

	        <form method="post" action="<?= $_baseurl . $_language?>/home/contact" id="contact-form" <? /* onSubmit="_gaq.push(['_trackEvent', 'Contact', 'Submit']);" */ ?>>
	            <input type="hidden" name="contact" value="1">

				<div class="row">
	        		<input type="text" name="name" placeholder="<?= ML::label('contact name') ?>">
	        	</div>

				<div class="row">
					<input type="email" name="email" placeholder="<?= ML::label('contact mail') ?>">
				</div>

				<div class="row">
					<input type="text" name="phone" placeholder="<?= ML::label('contact phone') ?>">
				</div>

				<? /*
				<div class="row">
					<input type="text" name="website" placeholder="<?= ML::label('contact website') ?>">
				</div> */ ?>

				<div class="row">
					<textarea name="message" placeholder="<?= ML::label('contact message') ?>"></textarea>

					<? /*
					<div class="custom-checkbox-wrap">
						<input type="checkbox" name="newsletter" id="subscribe">
						<label for="subscribe"><?= ML::label('subscribe check') ?></a></label>
					</div>
					*/ ?>

					<a id="contact-form-submit" class="button-submit" title="<?= ML::label("contact submit")?>" href="javascript:;"></a>
				</div>

				<div class="form-errors"></div>

	        </form>
		</div>

	</section>

	<section class="contact-address appear-effect">

		<div class="image">
			<img src="<?= $_baseurl . 'cms_img/' . $contact->file ?>" alt="<?= $contact->caption ?>">
		</div>

		<div class="address">
			<h3 class="h2">
				<?= $contact->address_title ?>
			</h3>

			<div class="text with-marker custom-text-content">
				<?
					echo \App\ViewHelper::replaceContentPlaceHolders($contact->address_text);
				?>
			</div>
		</div>

	</section>

</section>

