
			<footer class="main">

				<nav class="main-footer">
					<ul>
						<? foreach ($footerMenu as $item): ?>

						<li class="<?= $item->active ? 'active' : null ?>">
							<a href="<?= $item->url ?>">
								<?= $item->title ?>
							</a>
						</li>

						<? endforeach; ?>
					</ul>
				</nav>

				<div class="social-buttons social-menu-floater">

					<a class="facebook" target="_blank" href="https://www.facebook.com/Pixelindustries"></a>
					<a class="twitter" target="_blank" href="https://twitter.com/pxl_nl"></a>

				</div>

			</footer>