			<header class="main animated wait">

				<div class="top-bar">

					<a class="main-logo" href="<?= $this->route('') ?>">
						<img src="img/logo.svg" alt="PXL">
					</a>

					<div class="social-buttons social-menu-floater">

						<a class="facebook" target="_blank" href="https://www.facebook.com/Pixelindustries"></a>
						<a class="twitter" target="_blank" href="https://twitter.com/pxl_nl"></a>

						<? /*
						<a class="instagram" target="_blank" href="http://instagram.com/pixelindustries"></a>
						*/ ?>

					</div>

				</div>

				<nav class="main">
					<ul>
						<? foreach ($headerMenu as $item): ?>

						<li class="<?= $item->active ? 'active' : null ?>">
							<a href="<?= $item->url ?>">
								<?= $item->title ?>
							</a>
						</li>

						<? endforeach; ?>
					</ul>
				</nav>

			</header>
