			<header class="main">
				<div class="container">

					<div class="top-bar" data-0="opacity: 1;" data-510="opacity: 0;">

						<a class="main-logo" href="<?= $this->route('') ?>">
							<img src="img/logo.svg" alt="PXL">
						</a>

						<div class="social-buttons social-menu-floater">

							<a class="facebook" target="_blank" href="https://www.facebook.com/Pixelindustries"></a>
							<a class="twitter" target="_blank" href="https://twitter.com/pxl_nl"></a>

							<? /*
							<a class="instagram" target="_blank" href="http://instagram.com/pixelindustries"></a>
							*/ ?>

						</div>

					</div>

					<nav class="main" data-0="opacity: 1;" data-450="opacity: 0;">
						<ul>
							<? foreach ($headerMenu as $item): ?>

							<li class="<?= $item->active ? 'active' : null ?>">
								<a href="<?= $item->url ?>">
									<?= $item->title ?>
								</a>
							</li>

							<? endforeach; ?>
						</ul>
					</nav>

				</div>
			</header>


			<div class="mobile-menu-bg"></div>

			<div class="mobile-menu">
				<ul>
					<? foreach ($headerMenu as $item): ?>

					<li class="<?= $item->active ? 'active' : null ?>">
						<a href="<?= $item->url ?>">
							<?= $item->title ?>
							<? /*
							<span class="splitL"><?= $item->title ?></span>
							<span class="splitR"><?= $item->title ?></span>
							*/ ?>
						</a>
					</li>

					<? endforeach; ?>
				</ul>

				<div class="phone-number">
					+31 (0)23 532 34 32
				</div>
			</div>

			<div class="mobile-menu-header-overlay">

				<a class="main-logo" href="<?= $this->route('') ?>">
					<img src="img/logo_white.svg" alt="PXL">
				</a>

				<div class="mobile-menu-burger">
					<div class="x"></div>
					<div class="y"></div>
	                <div class="z"></div>
				</div>
			</div>
