<?
    $videoImage = $_baseurl . 'cms_img/_video/' . 'team.jpg';
    $videoUrl   = $_baseurl . 'cms_img/_video/' . 'team.mp4';

?>

<div class="video-container">

    <video id="<?= $videoId ?>"
        poster="<?= $videoImage ?>"
        src="<?= $videoUrl ?>"
        <? if ($isMobile): ?>autoplay="autoplay"<? endif; ?>
        data-is-mobile="<?= ($isMobile) ? 1 : null ?>"
    ></video>

</div>
