<div id="gmaps" class="maps">
	<div id="map-canvas"></div>
	
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
	<script type="text/javascript">

	if (document.getElementById('map-canvas')){
	 
	   	var myLatlng = new google.maps.LatLng(52.38839,4.64270);

	   	var styles = [
		    {
		      stylers: [
		        { saturation: -100 }
		      ]
		    }
		];

	  	var panoramaOptions = {
		  position: myLatlng,
		  pov: {
		    heading: 90,
		    pitch: 9,

		  },
	        linksControl: true,
	        disableDefaultUI: true,
	        center: myLatlng,
	        streetViewControl: false,
	        draggable:true,
	        scrollwheel: false,
	        mapTypeControlOptions: {
		      	mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'map_style']
		    },
		    zoomControl: false,
		    panControl: false
		};
		var panorama = new  google.maps.StreetViewPanorama(document.getElementById("map-canvas"), panoramaOptions);

	}
	</script>
</div>