<?
    $videoImage = $_baseurl . 'cms_img/_video/' . 'mission.jpg';
    $videoUrl   = $_baseurl . 'cms_img/_video/' . 'mission.mp4';


    // smaller alternative for mobile
    // actually just a picture for now
    if ( ! $isMobile && ! $isTablet):
?>

<div class="video-container">

    <video
        poster="<?= $videoImage ?>"
        autoplay="autoplay"
        src="<?= $videoUrl ?>"
    ></video>

</div>

<?
    else:
        $videoImage = $_baseurl . 'cms_img/_video/' . 'mission_mobile.png';
?>

<div class="video-container image">

    <img src="<?= $videoImage ?>" alt="Mission">

</div>

<? endif; ?>