<?
	/*
	 * Expecting social feed data...
	 * not sure what the plan is exactly
	 *
	 * ...
	 */
?>

	<div class="block-group left">
		<div class="block large">
		</div>
	</div>

	<div class="block-group middle">
		<div class="block wide">
		</div>

		<div class="block small">
		</div>

		<div class="block small">
		</div>
	</div>

	<div class="block-group right">
		<div class="block large">
		</div>
	</div>