<?
	/*
	 * Expecting social feed data...
	 * not sure what the plan is exactly
	 *
	 * ...
	 */
?>

	<div class="block-group left">
		<div class="block large appear-effect">
		</div>
	</div>

	<div class="block-group middle">
		<div class="block wide appear-effect">
		</div>

		<div class="block small appear-effect">
		</div>

		<div class="block small appear-effect">
		</div>
	</div>

	<div class="block-group right">
		<div class="block large appear-effect">
		</div>
	</div>