<?php
	ob_end_clean();
	header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
	header("Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0");
	header("Pragma: no-cache");
	header('Content-type: application/json');
	
	if (!is_null($this->_resultData)) {
		$variables = $this->_resultData;
	} else {
		$variables = array();
		foreach(array_diff(array_keys($this->_variables), $this->_globalVariables) as $key) {
			$variables[$key] = $this->_variables[$key];
		}
	}

	// Return JSON to client, preserving booleans as booleans instead of strings
	exit(str_replace(array('"true"', '"false"'), array('true', 'false'), @json_encode($variables)));