<meta name="keywords" content="<?= $keywords; ?>" /> 
<meta name="description" content="<?= $description; ?>" /> 
<meta name="robots" content="<?= $robots; ?>" />

<title><?= $title; ?></title>

<?php if(!empty($next)): ?>
<link rel="next" href="<?= $next; ?>" />
<?php endif; ?>

<?php if(!empty($prev)): ?>
<link rel="prev" href="<?= $prev; ?>" />
<?php endif; ?>

<?php if(!empty($canonical)): ?>
<link rel="canonical" href="<?= $canonical; ?>" />
<?php endif; ?>

<?php foreach($meta as $k => $v): ?>
<meta name="<?= $k; ?>" content="<?= $v; ?>" />
<?php endforeach; ?>

<?php foreach($fbmeta as $k => $v): ?>
<meta property="og:<?= $k; ?>" content="<?= $v; ?>" />
<?php endforeach; ?>

<?php if(empty($fbmeta['title'])): ?>

<?php endif; ?>
