<?php
	namespace PXL\Core\Logging\Backend;
	use PXL\Core\Logging as L;
	use PXL\Core\Tools as T;

	class Emailer implements L\Backend {
		protected $sendTo;
		protected $body;

		public function __construct($sendTo) {
			$this->sendTo = $sendTo;
		}

		public function handle(L\LogEvent $le) {
			$this->body .= date('d-m-Y H:i:s', $le->timestamp).':<br />'$le->message.'<br /><hr /><br />';
		}

		public function __destruct() {
			$e = new T\Emailer();
			$e->addressee($this->sendTo);
			$e->sender('logger@core.pixelindustries.com');
			$e->subject('Logmessage (generated by PXL Core)');
			$e->messageHtml($this->body);
			$e->send();
		}
	}