
<section class="banner-video home-video no-margin-column appear-effect<?= ($isMobile) ? ' mobile' : null ?>">
<?
	$this->partial('home-video-content', array(), '_parts');
?>
</section>


<section class="home-services large-margin-column">

	<? foreach ($services as $service): ?>
	<?
		$url = $this->route('services', $service->slug);
	?>

	<section class="service appear-effect">

		<header>
			<a href="<?= $url ?>">
				<div class="icon service-<?= $service->icon ?>"></div>
				<h2 class="h2">
					<?= $service->title ?>
				</h2>
			</a>
		</header>

		<section class="custom-text-content">
			<?= $service->intro ?>
		</section>

		<footer>
			<a class="arrow-link" href="<?= $url ?>">
				<span class="arrow"></span>
				<?= $service->title ?>
			</a>
		</footer>

	</section>


	<? endforeach; ?>

</section>



<section class="cases cases-banner no-margin-column">
<?
	$this->partial('cases-banner-content', array('cases' => $cases), '_parts');
?>
</section>


<? if ( ! empty($blog)): ?>

<section class="home-blog large-margin-column appear-effect">

	<div class="owl-carousel">

		<?
			foreach ($blog as $post) {

				$this->partial('_post', array('post' => $post), 'blog');
			}
		?>

	</div>

</section>

<? endif; ?>


<? if ( ! $isMobile): ?>

<section class="home-social social-banner no-margin-column">
<?
	$this->partial('social-banner-content', array('social' => $social), '_parts');
?>
</section>

<? endif; ?>


<section class="home-contact-and-location large-margin-column">

	<section class="home-contact appear-effect">

		<h3 class="h2">
			<?= ML::label('work with us') ?>
		</h3>

		<p>
			<?= ML::label('work with us paragraph') ?>
		</p>

		<hr>

		<div id="contact-form-thanks">
			<?= ML::label('contact thanks') ?>
		</div>

		<div id="contact-form-container" class="basic-form contact-form">

	        <form method="post" action="<?= $_baseurl . $_language?>/home/contact" id="contact-form" <? /* onSubmit="_gaq.push(['_trackEvent', 'Contact', 'Submit']);" */ ?>>
	            <input type="hidden" name="contact" value="1">

				<div class="row">
	        		<input type="text" name="name" placeholder="<?= ML::label('contact name') ?>">
	        	</div>

				<div class="row">
					<input type="email" name="email" placeholder="<?= ML::label('contact mail') ?>">
				</div>

				<div class="row">
					<!-- <input type="text" name="phone" placeholder="<?=ML::label('contact phone')?>" /> -->
				</div>

				<div class="row">
					<input type="text" name="website" placeholder="<?= ML::label('contact website') ?>">
				</div>

				<div class="row">
					<textarea name="message" placeholder="<?= ML::label('contact message') ?>"></textarea>

					<? /*
					<div class="custom-checkbox-wrap">
						<input type="checkbox" name="newsletter" id="subscribe">
						<label for="subscribe"><?= ML::label('subscribe check') ?></a></label>
					</div>
					*/ ?>

					<a id="contact-form-submit" class="button-submit" title="<?= ML::label("contact submit")?>" href="javascript:;"></a>
				</div>

				<div class="form-errors"></div>

	        </form>
		</div>

	</section>

	<section class="home-location appear-effect">

		<?
			// get distance if avaible... how?
		?>
		<section class="home-location-address">

			<h3 class="h2">
				<?= ML::label('We are just %DISTANCE% away') ?>
			</h3>

			<div class="address">

		    	<p class="with-marker">
		        	Prinsen Bolwerk 5<br/>
		        	2011MA Haarlem
		        </p>
				<p>
		        	+31 (0)23 532 34 32<br/>
		        	<a href="mailto:info@pixelindustries.com">info@pixelindustries.com</a>
		        </p>
		    </div>

		</section>

		<section class="home-location-video">

			<h3 class="h2">
				<?= ML::label('Get an inside view...') ?>
			</h3>

			<div class="video">

			</div>

		</section>

	</section>

</section>



<? /*
<div id="home"></div>

<div id="page" class="home">

	<div class="block count">
		<div class="inner">
			<h2 class="tagline"><?=$_content->page_title?></h2>

			<div class="numbers">
				<div class="item">
					<div class="image">
						<img src="<?=$_baseurl;?>img/why/code.png"/>
					</div>
					<div class="total counter" data-number="20.000" data-decimals="3">
						0
					</div>
					<div class="total-tagline">
						<?=ML::label('regels code')?>
					</div>
				</div>
				<div class="item">
					<div class="image">
						<img src="<?=$_baseurl;?>img/why/diamond.png"/>
					</div>
					<div class="total counter" data-number="35">
						0
					</div>
					<div class="total-tagline">
						<?=ML::label('briljante mensen'); ?>
					</div>
				</div>
				<div class="item">
					<div class="image">
						<img src="<?=$_baseurl;?>img/why/websites.png"/>
					</div>
					<div class="total counter" data-number="634">
						0
					</div>
					<div class="total-tagline">
						<?=ML::label('websites'); ?>
					</div>
				</div>
				<div class="item last">
					<div class="image">
						<img src="<?=$_baseurl;?>img/why/coffee.png"/>
					</div>
					<div class="total counter" data-number="62.012" data-decimals="3">
						0
					</div>
					<div class="total-tagline">
						<?=ML::label('kopjes koffie'); ?>
					</div>
				</div>
			</div>

			<p class="text">
				<?=$_content->page_text?>
			</p>
		</div>
	</div>


	<div class="block">
		<? if(!$isMobile): ?>
			<img class="<?=$isTablet ? 'tablet' : ''?>" src="<?=$_baseurl?>img/clients.jpg" />
		<? else: ?>
			<div class="clients"></div>
		<? endif; ?>
	</div>
	<div class="block grey team">
		<div class="inner">
			<h2>Team</h2>
			<div class="text">
				<?=ML::label('team content')?>
			</div>
		</div>

		<div id="team">
			<div id="viewport" class="anim">
				<div id="wrapper">
					<div id="scroller">
						<? foreach($employees as $e): ?>
							<div class="slide">
								<figure>
									<img class="inner-slide" src="<?=$_baseurl?>cms_img/<?=$isMobile && !$isTablet ? 'mobile_' : ''?><?=$isTablet ? 'tablet_' : ''?><?=$e->file?>">
									<div class="team-content">
										<div class="name"><?=$e->name?></div>
										<div class="role"><?=$e->role?></div>
									</div>
								</figure>
							</div>
						<? endforeach; ?>
					</div>
				</div>
			</div>
		</div>

	</div>
	<div class="block">
		<div class="inner partners-block">
			<h2>Partners</h2>
			<div class="text">
				<?=ML::label('partners content')?>
			</div>
			<? if(!$isMobile): ?>
			<div class="partners">
				<? foreach($partners as $p): ?>
					<a href="<?=$_baseurl.$_language?>/partners/<?=$p->slug?>"><img class="partner" src="<?=$_baseurl?>cms_img/<?=$isMobile ? 'mobile_' : 'overview'?>_<?=$p->logo?>" /></a>
				<? endforeach; ?>
			</div>
			<? else: ?>
				<div class="partners"></div>
			<? endif; ?>
		</div>
	</div>
	<div class="block grey maps">

		<div class="inner">

			<div class="contact">
				<div id="contact-inner-thank"></div>
				<div id="contact-inner">
					<h2><?=ML::label('contact us')?></h2>

					 <div class="address">
			        	<div class="left">
			            	Prinsen Bolwerk 5<br/>
			            	2011MA Haarlem
			            </div>
			            <div class="right">
			            	+31 23 532 34 32<br/>
			            	<a href="mailto:info@pixelindustries.com">info@pixelindustries.com</a>
			        	</div>
			        </div>

			        <form method="post" action="<?=$_baseurl.$_language?>/home/contact" id="contactform" onSubmit="_gaq.push(['_trackEvent', 'Contact', 'Submit']);">
			        	<input type="text" name="name" placeholder="<?=ML::label('contact name')?>" />
						<input type="email" name="email" placeholder="<?=ML::label('contact mail')?>" />
						<!-- <input type="text" name="phone" placeholder="<?=ML::label('contact phone')?>" /> -->

						<textarea name="message" placeholder="<?=ML::label('contact message')?>"></textarea>

						<div class="custom-checkbox-wrap">
							<input type="checkbox" name="newsletter" id="subscribe" />
							<label for="subscribe"><?=ML::label('subscribe check');?></a></label>
						</div>

						<a class="btn black"><?= ML::label("contact submit")?></a>

			            <input type="hidden" name="contact" value="1" />
			        </form>
				</div>
			</div>
		</div>
		<div class="newsletter">
			<div id="newsletter-inner-thank"></div>
			<div id="newsletter-inner">
				<h2><?=ML::label('newsletter')?></h2>

				<div class="text">
					<?=ML::label('subscribe now')?>
				</div>

				<form action="<?=$_baseurl.$_language?>/home/newsletter"id="newsletterform">
					<input type="hidden" name="newsletter" value="1">
					<ul>
						<li><input type="text" name="name" placeholder="<?=ML::label('contact name')?>"/></li>
						<li><input type="email" name="email" placeholder="<?=ML::label('contact email')?>"/></li>
						<li><button type="submit"><?=ML::label('contact subscribe')?></button>
					</ul>
				</form>
			</div>
		</div>
		<div class="thankyou"></div>
	</div>
</div>
*/?>