
<section class="banner-video home-video no-margin-column <?= ($isMobile) ? ' mobile' : null ?>">
<?
	$this->partial('home-video-content', array(), '_parts');
?>
</section>


<section class="home-services large-margin-column">

	<? foreach ($services as $service): ?>
	<?
		$url = $this->route('services', $service->slug);
	?>

	<section class="service appear-effect">

		<header>
			<a href="<?= $url ?>">
				<div class="icon service-<?= $service->icon ?>"></div>
				<h2 class="h2">
					<?= $service->title ?>
				</h2>
			</a>
		</header>

		<section class="custom-text-content">
			<?= $service->intro ?>
		</section>

		<footer>
			<a class="arrow-link" href="<?= $url ?>">
				<span class="arrow"></span>
				<?= $service->title ?>
			</a>
		</footer>

	</section>


	<? endforeach; ?>

</section>



<section class="cases cases-banner no-margin-column">
<?
	$this->partial('cases-banner-content', array('cases' => $cases), '_parts');
?>
</section>


<? if ( ! empty($blog)): ?>

<section class="home-blog large-margin-column appear-effect">

	<div class="owl-carousel">

		<?
			foreach ($blog as $post) {

				$this->partial('_post', array('post' => $post, 'disableAppearEffect' => true), 'blog');
			}
		?>

	</div>

</section>

<? endif; ?>


<? if ( ! $isMobile && count($social) >= 5): ?>

<section class="home-social social-banner no-margin-column">
<?
	$this->partial('social-banner-content', array('social' => $social), '_parts');
?>
</section>

<? endif; ?>


<section class="home-contact-and-location large-margin-column">

	<section class="home-contact appear-effect">

		<h3 class="h2">
			<?= ML::label('work with us') ?>
		</h3>

		<p>
			<?= ML::label('work with us paragraph') ?>
		</p>

		<hr>

		<div id="contact-form-thanks">
			<?= ML::label('contact thanks') ?>
		</div>

		<div id="contact-form-container" class="basic-form contact-form">

	        <form method="post" action="<?= $_baseurl . $_language?>/home/contact" id="contact-form" <? /* onSubmit="_gaq.push(['_trackEvent', 'Contact', 'Submit']);" */ ?>>
	            <input type="hidden" name="contact" value="1">

				<div class="row">
	        		<input type="text" name="name" placeholder="<?= ML::label('contact name') ?>">
	        	</div>

				<div class="row">
					<input type="email" name="email" placeholder="<?= ML::label('contact mail') ?>">
				</div>

				<div class="row">
					<input type="text" name="phone" placeholder="<?= ML::label('contact phone') ?>">
				</div>

				<? /*
				<div class="row">
					<input type="text" name="website" placeholder="<?= ML::label('contact website') ?>">
				</div> */ ?>

				<div class="row">
					<textarea name="message" placeholder="<?= ML::label('contact message') ?>"></textarea>

					<? /*
					<div class="custom-checkbox-wrap">
						<input type="checkbox" name="newsletter" id="subscribe">
						<label for="subscribe"><?= ML::label('subscribe check') ?></a></label>
					</div>
					*/ ?>

					<a id="contact-form-submit" class="button-submit" title="<?= ML::label("contact submit")?>" href="javascript:;"></a>
				</div>

				<div class="form-errors"></div>

	        </form>
		</div>

	</section>

	<section class="home-location appear-effect">

		<?
			// get distance if avaible... how?
		?>
		<section class="home-location-address">

			<h3 class="h2">
				<?= ML::label('We are just %DISTANCE% away') ?>
			</h3>

			<div class="address">

		    	<p class="with-marker">
		        	Prinsen Bolwerk 5<br/>
		        	2011 MA Haarlem
		        </p>
				<p>
		        	+31 (0)23 532 34 32<br/>
		        	<a href="mailto:info@pixelindustries.com">info@pixelindustries.com</a>
		        </p>
		    </div>

		</section>

		<section class="home-location-video">

			<h3 class="h2">
				<?= ML::label('Get an inside view...') ?>
			</h3>

			<div class="video">

			</div>

		</section>

	</section>

</section>
