<!DOCTYPE html>
<html lang="<?= $_language ?>">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1<?= $notUserScalable ? ', user-scalable=no' : null ?>">

		<meta property="og:site_name" content="Pixelindustries">

		<? if ( ! empty($case->slug)) : ?>
			<meta property="og:title" content="Pixelindustries | <?= $case->name ?>">
			<meta property="og:type" content="website">
			<meta property="og:url" content="<?= $_baseurl . $_language?>/cases/<?= $case->slug ?>">
			<meta property="og:image" content="<?= $_baseurl ?>/cms_img/overview_<?= $case->file ?>">
			<meta property="og:description" content="<?= strip_tags($case->main_description) ?>">
		<? endif ?>

		<? if ( ! empty($post->slug)) : /* blog */ ?>
			<meta property="og:title" content="Pixelindustries | Blog | <?= $post->title ?>">
			<meta property="og:type" content="website">
			<meta property="og:url" content="<?= $_baseurl . $_language?>/blog/<?= $post->slug ?>">
			<meta property="og:image" content="<?= $_baseurl ?>/cms_img/overview_<?= $post->file ?>">
			<meta property="og:description" content="<?= strip_tags($post->intro) ?>">
		<? endif ?>

		<? if( ! empty($partner->slug)): ?>
            <meta property="og:title" content="Pixelindustries | <?= $partner->name ?>">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language?>/partners/<?= $partner->slug ?>">
            <meta property="og:image" content="<?= $_baseurl?>/cms_img/overview_<?= $partner->logo ?>">
            <meta property="og:description" content="<?= strip_tags($partner->main_description) ?>">
        <? endif; ?>

        <? if( ! empty($jobs)): ?>
        	<meta property="og:title" content="Pixelindustries">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language ?>/jobs">
            <meta property="og:image" content="http://www.pixelindustries.com/img/jobs.png">
            <meta property="og:description" content="Werken bij een internet bureau iets voor jou? Het tofste internet bureau van Haarlem heeft nog vacatures open staan.">
	    <? endif; ?>

 		<? $this->seo(); ?>

		<base href="<?= $_baseurl ?>">

		<link rel="shortcut icon" href="img/favicon.ico">

		<link rel="stylesheet" href="<?= $_baseurl . 'css/default.css' ?>">

		<!--[if IE]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie.css'; ?>">
		<![endif]-->

		<? /*
		<!--[if IE 9]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie9.css'; ?>">
		<![endif]-->

		<!--[if IE 8]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie8.css'; ?>">
		<![endif]-->

		<!--[if IE 7]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie7.css'; ?>">
		<![endif]-->
		*/ ?>
		<?
			if (file_exists(APPLICATION_PATH . 'webroot/css/' . $controllerName . '.css')) {
				$this->includeCss('css/' . $controllerName . '.css');
			}

			$this->css();
		?>

	</head>
	<body<?= $hasParallax && ! ($isMobile || $isTablet) ? ' class="has-parallax"' : null ?> data-rocket-offset="1500" data-rocket-bottom="100"<?=
		! empty($pxlLocation) ? ' data-pxl-latitude="' . $pxlLocation->latitude . '" data-pxl-longitude="' . $pxlLocation->longitude . '"' : null ?>>

		<!--[if lt IE 9]>
		<div id="old-browser-warning" class="top-notification-bar">
			Je browser is een leuk stukje antiek. Probeer eens een nieuwere, dat zou je webgaande leven een stuk prettiger maken
			&mdash; en dan werkt deze site ook lekker.
		</div>
		<![endif]-->

		<div class="main-container">

			<?
				$this->partial('__header', array(), '_parts');
			?>

			<div id="main" class="content-container <?= $isTablet ? 'page_tablet' : '' ?>">
				<?
					$this->contents();
				?>

				<div id="pxl-rocket" class="scroll-to-top"><div></div></div>
			</div>

			<?
				$this->partial('__footer', array(), '_parts');
			?>

		</div>

		<? if ($doPreroll): ?>

		<div id="preroll-container">
			<div class="pxl">
				<img src="<?= $_baseurl .'img/logo.svg' ?>" alt=".PXL">
			</div>
		</div>

		<? endif; ?>

		<?
			$this->partial('__javascript_end', array(), '_parts');
		?>

	</body>
</html>