<!DOCTYPE html>
<html lang="<?= $_language ?>">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">

		<? if (!empty($case->slug)) : ?>
			<meta property="og:title" content="Pixelindustries | <?= $case->name ?>">
			<meta property="og:type" content="website">
			<meta property="og:url" content="<?= $_baseurl . $_language?>/cases/<?= $case->slug ?>">
			<meta property="og:image" content="<?= $_baseurl ?>/cms_img/overview_<?= $case->file ?>">
			<meta property="og:site_name" content="Pixelindustries">
			<meta property="og:description" content="<?= strip_tags($case->main_description) ?>">
		<? endif ?>

		<? if(!empty($partner->slug)): ?>
            <meta property="og:title" content="Pixelindustries | <?= $partner->name ?>">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language?>/partners/<?= $partner->slug ?>">
            <meta property="og:image" content="<?= $_baseurl?>/cms_img/overview_<?= $partner->logo ?>">
            <meta property="og:site_name" content="Pixelindustries">
            <meta property="og:description" content="<?= strip_tags($partner->main_description) ?>">
        <? endif; ?>

        <? if(!empty($jobs)): ?>
        	<meta property="og:title" content="Pixelindustries">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language ?>/jobs">
            <meta property="og:image" content="http://www.pixelindustries.com/img/jobs.png">
            <meta property="og:site_name" content="Pixelindustries">
            <meta property="og:description" content="Werken bij een internet bureau iets voor jou? Het tofste internet bureau van Haarlem heeft nog vacatures open staan.">
	    <? endif; ?>

 		<? $this->seo(); ?>

		<base href="<?= $_baseurl ?>">

		<link rel="shortcut icon" href="img/favicon.ico">

		<? /*
		<link rel="stylesheet" href="<?= $_baseurl . 'css/fixes.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/animate.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/fonts.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/controls.css' ?>">
		*/ ?>

		<link rel="stylesheet" href="<?= $_baseurl . 'css/default.css' ?>">

		<link href='//fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>

		<?php /*
		<!--[if IE 9]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie9.css'; ?>">
		<![endif]-->

		<!--[if IE 8]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie8.css'; ?>">
		<![endif]-->

		<!--[if IE 7]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie7.css'; ?>">
		<![endif]-->
		*/ ?>

		<? $this->css(); ?>

	</head>
	<body class="animatedsuperslow">

		<div class="main-container">

			<?
				$this->partial('__header', array(), '_parts');
			?>

			<div id="main" class="<?= $isTablet ? 'page_tablet' : '' ?>">
				<?
					$this->contents();
				?>
			</div>

			<div id="cursor"></div>

			<?
				$this->partial('__footer', array(), '_parts');
			?>

		</div>

		<?
			$this->partial('__javascript_end', array(), '_parts');
		?>

	</body>
</html>