<!DOCTYPE html>
<html lang="<?= $_language ?>">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">

		<? if (!empty($case->slug)) : ?>
			<meta property="og:title" content="Pixelindustries | <?= $case->name ?>">
			<meta property="og:type" content="website">
			<meta property="og:url" content="<?= $_baseurl . $_language?>/cases/<?= $case->slug ?>">
			<meta property="og:image" content="<?= $_baseurl ?>/cms_img/overview_<?= $case->file ?>">
			<meta property="og:site_name" content="Pixelindustries">
			<meta property="og:description" content="<?= strip_tags($case->main_description) ?>">
		<? endif ?>

		<? if(!empty($partner->slug)): ?>
            <meta property="og:title" content="Pixelindustries | <?= $partner->name ?>">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language?>/partners/<?= $partner->slug ?>">
            <meta property="og:image" content="<?= $_baseurl?>/cms_img/overview_<?= $partner->logo ?>">
            <meta property="og:site_name" content="Pixelindustries">
            <meta property="og:description" content="<?= strip_tags($partner->main_description) ?>">
        <? endif; ?>

        <? if(!empty($jobs)): ?>
        	<meta property="og:title" content="Pixelindustries">
            <meta property="og:type" content="website">
            <meta property="og:url" content="<?= $_baseurl . $_language ?>/jobs">
            <meta property="og:image" content="http://www.pixelindustries.com/img/jobs.png">
            <meta property="og:site_name" content="Pixelindustries">
            <meta property="og:description" content="Werken bij een internet bureau iets voor jou? Het tofste internet bureau van Haarlem heeft nog vacatures open staan.">
	    <? endif; ?>

 		<? $this->seo(); ?>

		<base href="<?= $_baseurl ?>">

		<link rel="shortcut icon" href="img/favicon.ico">

		<? /*
		<link rel="stylesheet" href="<?= $_baseurl . 'css/fixes.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/animate.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/fonts.css' ?>">
		<link rel="stylesheet" href="<?= $_baseurl . 'css/controls.css' ?>">
		*/ ?>

		<link rel="stylesheet" href="<?= $_baseurl . 'css/default.css' ?>">

		<link href='//fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>


		<!--[if IE 9]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie9.css'; ?>">
		<![endif]-->

		<!--[if IE 8]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie8.css'; ?>">
		<![endif]-->

		<!--[if IE 7]>
			<link rel="stylesheet" href="<?= $_baseurl . 'css/ie/ie7.css'; ?>">
		<![endif]-->

		<? $this->css(); ?>

	</head>
	<body class="animatedsuperslow">

		<div id="container">
			<header class="animated wait">
				<nav class="inner">
					<span class="logo">
						<a href="<?= $_baseurl . $_language?>/home">
							<img src="img/<?= $isMobileTablet ? 'logo_mobile' : 'logo' ?>.png" alt="PXL">
						</a>
					</span>

					<span class="menu"></span>

					<div class="m_items">
						<!-- <span class="m_item"><a class="<?= $_content->type_of_page == 'home' ? 'active' : '' ?>" href="<?= $_baseurl . $_language ?>/home">Pixelindustries</a></span> -->
						<span class="m_item">
							<a class="<?= $_content->type_of_page == 'cases' ? 'active' : '' ?>" href="<?= $_baseurl . $_language ?>/cases">
								Cases
							</a>
						</span>
						<span class="m_item">
							<a class="<?= $_content->type_of_page == 'team' ? 'active' : '' ?>" href="<?= $_baseurl . $_language ?>/team">
								Team
							</a>
						</span>
						<span class="m_item">
							<a class="<?= $_content->type_of_page == 'jobs' ? 'active' : '' ?>" href="<?= $_baseurl . $_language ?>/jobs">
								Jobs
							</a>
						</span>
						<span class="m_item">
							<a class="<?= $_content->type_of_page == 'contact' ? 'active' : '' ?>" href="<?= $_baseurl . $_language ?>/contact">
								Contact
							</a>
						</span>
					</div>

					<span class="right">
						<span class="txt"><?=ML::label('follow us')?></span>
						<a target="_blank" href="https://www.facebook.com/Pixelindustries"><span class="social fb"></span></a>
						<a target="_blank" href="https://twitter.com/pxl_nl"><span class="social tw"></span></a>
						<a target="_blank" href="http://instagram.com/pixelindustries"><span class="social in"></span></a>
					</span>
				</nav>
			</header>
			<div id="main" class="<?= $isTablet ? 'page_tablet' : '' ?>">
				<?
					$this->contents();
				?>
			</div>
			<div id="cursor"></div>
		</div>


		<?
			$this->partial('__javascript_end', array(), '_parts');
		?>

	</body>
</html>