
<section class="blog-search large-margin-column">

	<form id="blog-search-form" class="blog-search-form" method="post" action="<?= $this->route('blog', 'search') ?>" data-always-focus="<?= $alwaysFocusInput ? 1 : 0 ?>">
		<div class="input-container">
			<input id="blog-search-input" type="search" name="search" value="<?= $search ?>" placeholder="<?= ML::label('search for something') ?>">
			<span class="input-icon"></span>
			<span id="blog-search-is-loading" class="loading-indicator dark in-input-container"></span>
		</div>
	</form>

</section>


<div id="blog-list-gutter-size">&nbsp;</div>
<section id="blog-list-container" class="blog-list large-margin-column"<?=
	(empty($blog) || !count($blog)) ? ' style="display: none;"' : null ?> data-page-on-open="<?= $currentPage ?>">

	<?
		foreach ($blog as $post) {
			$this->partial('_post', array( 'post' => $post ));
		}
	?>

</section>

<section id="blog-list-empty" class="blog-list blog-list-empty large-margin-column"<?= !( empty($blog) || !count($blog)) ? ' style="display: none;"' : null ?>>

	<div class="warning">
		<?= ML::label('blog empty') ?>
	</div>

</section>




<? if ( ! $noAjaxPages && $currentPage < $finalPage): ?>

<section id="blog-next-page" class="blog-next large-margin-column">

	<hr>

	<a id="blog-next-page-load" href="<?= $_baseurl . $this->route('blog', '', array($currentPage + 1)) ?>" class="button default" data-current-page="<?= $currentPage ?>" data-final-page="<?= $finalPage ?>" data-url-base="<?= $_baseurl . $this->route('blog') ?>">
		<?= ML::label('blog more link') ?>
		<span id="blog-next-is-loading" class="loading-indicator"></span>
	</a>

</section>

<? endif; ?>