

<section class="jobs-detail-banner no-margin-column <?=  ! ($isMobile || $isTablet) ? 'parallax-banner' : 'mobile' ?>"
	<? if ( ! ($isMobile || $isTablet)): ?>
	data-anchor-target="#main-parallax-end" data-0="transform: translate3d(0px, 0%, 0px);" data-<?= $headerDesktopHeight ?>-top-top="transform: translate3d(0px, -7.5%, 0px)"
	<? endif; ?>
>
	<div class="container" style="background-image: url('<?= $_baseurl . 'cms_img/' . $post->banner ?>')"
		<? if ( ! ($isMobile || $isTablet)): ?>
		data-0="opacity: 1" data-<?= $headerDesktopHeight ?>-top-top="opacity: 0" data-anchor-target="#main-parallax-end"
		<? endif; ?>
	>

		<div class="title">
			<h1 class="h1 bold-and-light"
				<? if ( ! ($isMobile || $isTablet)): ?>
				data-0="opacity: 1; transform: translate3d(0px, 0%, 0px)" data-<?= $headerDesktopHeight ?>-top-top="opacity: 0; transform: translate3d(0px, -90%, 0px)" data-anchor-target="#main-parallax-end"
				<? endif; ?>
			>
				<?= ! empty($job->fancy_title) ? $job->fancy_title : $job->name ?>
			</h1>

			<div class="info"
				<? if ( ! ($isMobile || $isTablet)): ?>
				data-0="opacity: 1; transform: translate3d(0px, 0%, 0px)" data-<?= $headerDesktopHeight ?>-top-top="opacity: 0; transform: translate3d(0px, -75%, 0px)" data-anchor-target="#main-parallax-end"
				<? endif; ?>
			>

				<span class="hours" title="<?= ML::label('jobs hours') ?>">
					<?= $job->hours ?>
				</span>

				<span class="starting" title="<?= ML::label('jobs starting') ?>">
					<?= $job->starting ?>
				</span>

			</div>
		</div>

	</div>

</section>

<? if ( ! ($isMobile || $isTablet)): ?>
<div class="parallax-offset-filler"></div>
<? endif; ?>

<div id="main-parallax-end" class="non-parallax-container">

	<section class="jobs-detail-title large-margin-column">

		<div class="title h1">
			<?= ML::label('jobs detail general title') ?>
		</div>

	</section>


	<section class="jobs-detail-icons no-margin-column appear-effect">

		<div class="icon-container left">
			<div class="image" style="background-image: url('<?=
				$_baseurl . 'cms_img/' . $icons->left_file ?>')"></div>

			<div class="title">
				<?= $icons->left_caption ?>
			</div>

			<div class="caption">
				<?= $job->caption_left ?>
			</div>
		</div>

		<div class="icon-container middle">
			<div class="image" style="background-image: url('<?=
				$_baseurl . 'cms_img/' . $icons->middle_file ?>')"></div>

			<div class="title">
				<?= $icons->middle_caption ?>
			</div>

			<div class="caption">
				<?= $job->caption_middle ?>
			</div>
		</div>

		<div class="icon-container right">
			<div class="image" style="background-image: url('<?=
				$_baseurl . 'cms_img/' . $icons->right_file ?>')"></div>

			<div class="title">
				<?= $icons->right_caption ?>
			</div>

			<div class="caption">
				<?= $job->caption_right ?>
			</div>
		</div>

	</section>


	<hr class="jobs-detail appear-effect">


	<section class="jobs-detail-content large-margin-column appear-effect">

		<div class="title h1 standard-middle-column">
			<?= $job->name ?>
		</div>

		<? if ( ! empty($colleagues) && count($colleagues)): ?>

		<div class="colleagues">

			<div class="h2">
				<?= ML::label('jobs your colleagues') ?>
			</div>

			<ul>
				<? foreach ($colleagues as $colleague): ?>

				<li class="colleague" style="background-image: url('<?=
					$_baseurl . 'cms_img/' . $colleague->file ?>')" title="<?= $colleague->name ?>"></li>

				<? endforeach; ?>
			</ul>

		</div>

		<? endif; ?>

		<div class="content custom-text-content standard-middle-column">
			<?
				echo \App\ViewHelper::replaceContentPlaceHolders( $job->description );
			?>
		</div>

	</section>


	<hr class="jobs-detail appear-effect">


	<section class="jobs-detail-contact large-margin-column appear-effect">

		<div class="title h1 standard-middle-column">
			<?= ML::label('jobs detail contact title') ?>
		</div>

		<div class="text custom-text-content standard-middle-column">
			<?
				echo \App\ViewHelper::replaceContentPlaceHolders( $job->contact_description );
			?>
		</div>

	</section>

</div>