
<section class="jobs-banner parallax-banner no-margin-column">

	<div class="title">
		<h1 class="h1 bold-and-light">
			<?= $pageTitle ?>
		</h1>
	</div>

</section>


<section class="jobs-list large-margin-column">

	<? if ( ! empty($jobs) && count($jobs)): ?>

		<? foreach ($jobs as $job): ?>

		<article class="job standard-middle-column">
			<a href="<?= $this->route('jobs', $job->slug) ?>">

				<div class="image" style="background-image: url('<?= $_baseurl . 'cms_img/' . $job->file ?>')"></div>

				<div class="text">

					<div class="title">
						<span class="prefix">
							<?= ML::label('jobs are you our') ?>
						</span>
						<span class="name">
							<?= $job->name ?>
						</span>
					</div>

					<div class="info">

						<span class="hours" title="<?= ML::label('jobs hours') ?>">
							<?= $job->hours ?>
						</span>

						<span class="starting" title="<?= ML::label('jobs starting') ?>">
							<?= $job->starting ?>
						</span>

					</div>
				</div>

			</a>
		</article>

		<? endforeach; ?>

	<? else: ?>

		<div class="empty">
			<?= ML::label('jobs empty') ?>
		</div>

	<? endif; ?>

</section>


<section class="jobs-newsletter large-margin-column">

	<div class="intro standard-middle-column">
		<div class="h2">
			<?= ML::label('jobs newsletter title') ?>
		</div>

		<p>
			<?= ML::label('jobs newsletter paragraph') ?>
		</p>
	</div>

	<div class="form standard-middle-column">

		<form id="jobs-newsletter-form" action="<?= $this->route('jobs', 'newsletter') ?>" method="post">

			<div class="row">
				<input type="text" name="name" value="" placeholder="<?= ML::label('jobs newsletter full name') ?>">
			</div>

			<div class="row">
				<input type="email" name="email" value="" placeholder="<?= ML::label('jobs newsletter email') ?>">
				<a id="jobs-newsletter-form-submit" class="button-submit small" title="<?= ML::label("jobs newsletter submit")?>" href="javascript:;"></a>
			</div>

		</form>
	</div>

</section>

