

<header class="case">

	<div class="title">

		<div class="back-link">
			<a class="arrow-back-link black" href="<?= $this->route('cases') ?>">
				<?= ML::label('view all cases') ?>
			</a>
		</div>

		<div class="h1 <?= \App\ViewHelper::getScaleClassForHugeTitleByLength($case->name) ?>">
			<?= $case->name ?>
		</div>

	</div>

	<div class="subtitle">
		<?= $case->case_name ?>
	</div>

</header>


<section class="case-focal-imagery large-margin-column">

	<?
		$isVideo = ( ! empty($case->video));
	?>
	<div class="container <?= $isVideo ? 'video' : 'image' ?>">

		<? if ($isVideo): ?>
			<?
				// local video file? or youtube?
				if ( preg_match('#\.mp4$#i', trim($case->video)) ):

					// video image? hmm. could just get jpg with same file name..?
					//$videoImage
			?>
				<video
			        <? /* poster="<?= $videoImage ?>" */ ?>
			        autoplay="autoplay"
			        src="<?= trim($case->video) ?>"
			    ></video>

			<? else: ?>
				<?
					$videoUrl = $case->video;

					if ( ! preg_match('#^https?://#i')) {
						$videoUrl = 'http://www.youtube.com/embed/' . $videoUrl;
					}
				?>
				<iframe title="YouTube video player" class="youtube-player" type="text/html"
					width="100%" src="<?= $videoUrl ?>"  frameborder="0" allowFullScreen></iframe>

			<? endif ?>

		<? else: ?>
			<img src="<?= "{$_baseurl}cms_img/{$case->file}" ?>" alt="<?= $case->caption ?>">
		<? endif; ?>
	</div>

</section>




<section class="case-introduction appear-effect large-margin-column">

	<div class="text custom-text-content standard-middle-column">
		<?
			echo \App\ViewHelper::replaceContentPlaceHolders( $case->main_description );
		?>
	</div>

	<div class="case-link standard-middle-column">
		<a class="button default" target="_blank" href="<?= $case->url ?>">
			<?= ML::label('cases visit site') ?>
		</a>
	</div>

</section>


<?
	// render blocks of text with images next to them.
	//
	// note that there should NOT be more images than text-blocks

	$texts = array();

	for ($x = 1; $x <= 10; $x++) {
		if ( ! \App\ViewHelper::textFieldEmpty($case->{'text_section_' . $x})) {
			$texts[] = $case->{'text_section_' . $x};
		}
	}


	foreach ($texts as $index => $text):

		try {
			$image = $gallery->get($index);
		} catch (\Exception $e) {
			$image = null;
		}

?>

<section class="case-text large-margin-column<?= empty($image) ? ' text-only' : null ?>">

	<div class="text appear-effect">
		<div class="container custom-text-content">
			<?
				echo \App\ViewHelper::replaceContentPlaceHolders( $text );
			?>
		</div>
	</div>

	<? if ( ! empty($image)): ?>
	<div class="image appear-effect">
		<img src="<?= "{$_baseurl}cms_img/{$image->file}" ?>" alt="<?= $image->caption ?>">
	</div>
	<? endif; ?>

</section>

<? endforeach; ?>


<hr class="cases">


<footer class="case-share large-margin-col">

	<div class="share standard-middle-column">

		<span class="text">
			<?= ML::label('share') ?>
		</span>

		<div class="share-links">
			<a href="//twitter.com/share?text=<?= \App\ViewHelper::urlEncode( 'Pixelindustries: ' . $case->name )
				?>" class="twitter" title="Twitter" rel="no-follow" target="_blank">

				T
			</a>
			<a href="//www.facebook.com/sharer.php?u=<?= \App\ViewHelper::urlEncode( $_baseurl . $this->route('cases', $case->slug) )
				?>" class="facebook" title="Facebook" rel="no-follow" target="_blank">
				F
			</a>
		</div>

	</div>

</footer>
