
<section class="cases-showcase cases-banner no-margin-column appear-effect">
<?
	$this->partial('cases-banner-content', array('cases' => $showCases), '_parts');
?>
</section>


<section class="cases large-margin-column">

	<?
		/*
		 * The pattern to display these in will be managed by CSS
		 *
		 * Default/desktop is:
		 * 			[x] [x] [x]
		 * 			[xxxxx] [x]
		 * 			[x] [x] [x]
		 * 			[x] [xxxxx]
		 */
		$pattern = array(
			'', '', '',
			'wide', '',
			'', '', '',
			'', 'wide',
		);

		$maxToShow = 9;
	?>


	<?
		$c = 0;

		foreach ($cases as $case):
			if ($c > $maxToShow) break;
	?>

		<a class="case<?= isset($pattern[$c]) ? ' ' . $pattern[$c] : null ?> appear-effect" href="<?= $this->route('cases', $case->slug) ?>">
			<?
				$img = $_baseurl . 'cms_img/' . $case->file;
			?>

			<div class="image-container">
				<div class="image" style="background-image: url('<?= $img ?>')"></div>
				<div class="size-helper"></div>
			</div>

			<div class="caption">
				<div class="subtitle">
					<?= $case->name ?>
				</div>
				<div class="title">
					<?= $case->case_name ?>
				</div>
			</div>
		</a>

	<?
			$c++;
		endforeach;
	?>

</section>
